require('plugins.webdevicons')
require('plugins.indentline')
require('plugins.autopairs')
require('plugins.comment')
require('plugins.dashboard')
-- require('plugins.feline')
-- require('plugins.galaxyline')
require('plugins.statusline')
require('plugins.floaterm')
require('plugins.gitsigns')
require('plugins.lspkind')
require('plugins.lspsaga')
require('plugins.neogit')
require('plugins.neoscroll')
-- require('plugins.nord')
require('plugins.nvim-tree')
-- require('plugins.substrata')
require('plugins.telescope')
require('plugins.treesitter')
-- require('plugins.rooter')
-- require('plugins.stt')
require('plugins.toggleterm')
-- require('plugins.truezen')
-- require('plugins.tokyonight')
