require('plugins.webdevicons')
require('plugins.indentline')
require('plugins.autopairs')
require('plugins.comment')
-- require('plugins.dashboard')
require('plugins.galaxyline')
require('plugins.floaterm')
require('plugins.gitsigns')
require('plugins.lspkind')
require('plugins.neogit')
require('plugins.neoscroll')
-- require('plugins.nord')
require('plugins.nvim-tree')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.truezen')
