return {
  -- "angularls",
  "asm_lsp",
  -- "astro",
  "bashls",
  "clangd",
  "cmake",
  "cssls",
  "clojure_lsp",
  -- "crystalline",
  "dockerls",
  "docker_compose_language_service",
  "eslint",
  "emmet_language_server",
  -- "fennel_language_server",
  "gopls",
  "graphql",
  "html",
  "htmx",
  "jedi_language_server",
  "jqls",
  "jsonls",
  "kotlin_language_server",
  "lua_ls",
  "marksman",
  "mdx_analyzer",
  -- "nim_langserver",
  -- "swift_mesonls",
  -- "ocamllsp",
  "ols",
  "spectral",
  "psalm",
  "prismals",
  "rust_analyzer",
  -- "solargraph",
  "sqlls",
  "svelte",
  "taplo",
  "tailwindcss",
  "tsserver",
  -- "v_analyzer",
  -- "volar",
  "lemminx",
  "yamlls",
  -- "zls"
}
