add_newline = false

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[ ](bold fg:green)'
error_symbol = '[ ](bold fg:red)'
vimcmd_symbol = '[ ](bold fg:creen)'
vimcmd_replace_one_symbol = '[ ](bold fg:purple)'
vimcmd_replace_symbol = '[ ](bold fg:purple)'
vimcmd_visual_symbol = '[ ](bold fg:lavender)'

[conda]
disabled = true
ignore_base = true
